## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Cursos de sidemount avanzado"
theme = "hugo-story"
baseurl ="https://instructor.avances123.es/"
## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
googleAnalytics = "G-NFPNJYXW0E"


## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "Cursos de sidemount avanzado e introduccion al buceo tecnico"
  logo = "images/banner.jpg"
  favicon = true
  author = "Fabio Rueda"

[Params.social]
  github = "https://github.com/avances123/"
  twitter = "https://twitter.com/avances123"
  email = "avances123@gmail.com"
  instagram = "https://instagram.com/avances123"
  linkedin = "https://linkedin.com/avances123"
  telegram = "https://telegram.org"
