---
disableKinds: ["taxonomy", "taxonomyTerm"]
pluralizelisttitles: false
baseURL: https://www.sidemount.es
languageCode: es-es
title: Cursos de Sidemount Avanzado
theme: piko
paginate: "9"
copyright: 
googleAnalytics:
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
outputs:
  home:
  - HTML
  # - RSS
  # - JSON
minify:
  disableCSS: false
  disableHTML: false
  disableJS: false
  disableJSON: false
  disableSVG: false
  disableXML: false
  minifyOutput: true
  tdewolff:
    html:
      keepWhitespace: false

params:
  analytics:
    google:
      SiteVerificationTag: # Google Site Verification
    yandex:
      SiteVerificationTag: # Yandex Site Verification
    bing:
      SiteVerificationTag: # Bing Site Verification
  env: production
  author: Fabio Rueda
  description: Cursos de buceo tecnico en sidemount
  math: false
  images:
  - "/uploads/og.webp"
  label:
    title: _Sidemount Spain_
    text: Bienvenido a la web de Sidemount Spain
    lightNavIcon: /uploads/sun.svg
    darkNavIcon: /android-chrome-192x192.png
    iconHeight: "35"
    iconWIdth: "35"
  comments: false
  mainSections:
  - cursos
  ShowShareButtons: false
  ShowCodeCopyButtons: true
  ShowRelated: true
  CookieNotice: 
  CookieLink:
  CookieButton: Cookies Policy
  disableAnchoredHeadings: false
  contactFormAction: https://formsubmit.io/send/avances123@gmail.com
  assets:
    disableFingerprinting: false
    favicon: /favicon.ico
    favicon16x16: /favicon-16x16.png
    favicon32x32: /favicon-16x16.png
    apple_touch_icon: apple-touch-icon.png
    safari_pinned_tab: /favicon.ico
  ShowReadingTime: false
  ShowBreadCrumbs: true
  homepage:
    # Hero Section
    disableHeroSection: false
    heroUpperTitle:
    heroTitle: Sidemount Spain
    heroDescription: Entrenamiento avanzado en el buceo tecnico
    heroCTAPrimaryText: Contacto
    heroCTAPrimaryUrl: "/contacto/"
    heroCTASecondaryText: Por que sidemount?
    heroCTASecondaryUrl: "/articulos/"
    heroBackgroundImage: "/11.webp"
    # Blog Section
    disableBlogSection: true
    blogTitle: Historial
    blogDescription: Articulos de cursos y entrenos anteriores
    seeMoreText: Más Certificaciones
    # About Section    
    disableAboutSection: false
    aboutTitle: La mejor agencia de la industria
    aboutDescription: Obtendras tus carnets de la mejor certificadora
    aboutImgUrl: "/product_t_d_tdi_sticker_v2.1.jpg"
    aboutContent: Hi guys. This is where you put something about yourself.
    # Portfolio Section
    disablePortfolioSection: true
    portfolioTitle: Portfolio
    portfolioDescription: Some of my works
    portfolio:
    - imageUrl: /uploads/portfolio-1.webp
      alt: # image alt for better SEO
      description: 
      websiteUrl: 
    - imageUrl: /uploads/portfolio-1.webp
      alt: # image alt for better SEO
      description: 
      websiteUrl: 
    - imageUrl: /uploads/portfolio-2.webp
      alt: # image alt for better SEO
      description: Portfolio Two.
      websiteUrl: #
    - imageUrl: /uploads/portfolio-3.webp
      alt: # image alt for better SEO
      description: Portfolio Three.
      websiteUrl: #
  # Search Options (https://fusejs.io/)
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: "0"
    distance: "1000"
    threshold: "0.4"
    minMatchCharLength: "0"
    keys:
    - title
    - permalink
    - summary
    - content
  plugins:
    css:
    - link: plugins/css/pico.min.css
    js:
    - link: plugins/js/feather.min.js
menus:
  main: # Main Menu
  # - name: Blog
  #   title: Historial
  #   pre: activity
  #   url: "/blog"
  #   weight: "20"
  - name: Cursos
    title: Cursos
    pre: book-open
    url: "/cursos/"
    weight: "10"
  - name: Agenda
    title: Agenda
    pre: calendar
    url: "/agenda/"
    weight: "40"
  - name: Contact
    title: Contacto
    pre: mail
    url: "/contacto/"
    weight: "40"
  - name: Quiénes Somos
    title: Quiénes Somos
    pre: user
    url: "/staff/"
    weight: "40"
  - name: Canal de youtube
    title: 
    pre: youtube
    url: https://www.youtube.com/@sidemount_spain
    weight: "50"
  - name: Perfil instagram
    title: 
    pre: instagram
    url: https://www.instagram.com/sidemount_spain/
    weight: "60"
  search: # Search page's quick links
  - name: Categories
    title: Categories
    url: "/categories/"
    weight: "10"
  - name: Archives
    title: Archives
    url: "/archives/"
    weight: "20"
  - name: Tags
    title: Tags
    url: "/tags/"
    weight: "30"
